@echo on
echo Starting Clients...

echo Starting Client 1...
cd Clients\Client1
sh ./Client1.sh
echo Client1 started...
sleep 5

echo Starting Client 2...
cd ..\Client2
sh ./Client2.sh
echo Client2 started...
sleep 5

echo Starting Client 3...
cd ..\Client3
sh ./Client3.sh
echo Client3 started...
sleep 5

echo Starting Client 4...
cd ..\Client4
sh ./Client4.sh
echo Client4 started...
sleep 5

echo Starting Client 5...
cd ..\Client5
sh ./Client5.sh
echo Client5 started...
sleep 5

echo Starting Client 6...
cd ..\Client6
sh ./Client6.sh
echo Client6 started...
sleep 5

echo Starting Client 7...
cd ..\Client7
sh ./Client7.sh
echo Client7 started...
sleep 5

echo Starting Client 8...
cd ..\Client8
sh ./Client8.sh
echo Client8 started...
sleep 5

echo Starting Client 9...
cd ..\Client9
sh ./Client9.sh
echo Client9 started...
sleep 5

echo Starting Client 10...
cd ..\Client10
sh ./Client10.sh
echo Client10 started...
sleep 5

echo Exiting...
@echo off